#!/usr/bin/ruby

print "Loading railsrc..."
begin
  require 'hirb' # sudo gem install cldwalker-hirb --source http://gems.github.com
  Hirb.enable
rescue LoadError
end

def change_log(stream)
  ActiveRecord::Base.logger = Logger.new(stream)
  ActiveRecord::Base.clear_active_connections!
end

def show_log
  change_log(STDOUT)
end

def hide_log
  change_log(nil)
end

def he
    Hirb.enable
    puts "Hirb enabled."
end

def hd 
    Hirb.disable
    puts "Hirb disabled."
end

require 'logger'
Object.const_set(:RAILS_DEFAULT_LOGGER, Logger.new(STDOUT))
  
rails_root = File.basename(Dir.pwd)
IRB.conf[:PROMPT] ||= {}
IRB.conf[:PROMPT][:RAILS] = {
    :PROMPT_I => "#{rails_root}> ",
    :PROMPT_S => "#{rails_root}* ",
    :PROMPT_C => "#{rails_root}? ",
    :RETURN   => "=> %s\n" 
}
IRB.conf[:PROMPT_MODE] = :RAILS

puts "OK"

# begin
#   require 'hirb' # sudo gem install cldwalker-hirb --source http://gems.github.com
#   Hirb.enable
# rescue LoadError
# end
# 
# def change_log(stream)
#   ActiveRecord::Base.logger = Logger.new(stream)
#   ActiveRecord::Base.clear_active_connections!
# end
# 
# def show_log
#   change_log(STDOUT)
# end
# 
# def hide_log
#   change_log(nil)
# end
